# Generated by Django 4.1 on 2022-08-27 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero_protocolo',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='pessoa',
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome_servico',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=8)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autenticacao.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='servico',
            name='imagem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='autenticacao.imagem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='protocolo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='autenticacao.protocolo'),
            preserve_default=False,
        ),
    ]
