# Generated by Django 4.1 on 2022-08-27 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_imagem_remove_cliente_numero_protocolo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestacaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacao.imagem')),
                ('nome_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.cliente')),
                ('produto_comprado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacao.produto')),
                ('servico_prestado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacao.servico')),
                ('veiculo_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacao.veiculo')),
            ],
        ),
    ]
